# clone repo
---
- name: Delete backend
  file:
    state: absent
    path: repositories/Hackaton-2021

- name: Create the backend directory
  file:
    path: "repositories/Hackaton-2021"
    state: directory

- name: Clone project from github
  git:
    repo: "git@github.com:AGundak/Hackaton-2021.git"
    dest: "repositories/Hackaton-2021"
    version: master
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ id_rsa_key_path }}"

- name: Delete package-lock.json
  file:
    state: absent
    path: "repositories/Hackaton-2021/frontend/package-lock.json"

- name: Install frontend requirements
  command: npm i --force
  args:
    chdir: "repositories/Hackaton-2021/frontend"

- name: Build frontend
  command: npm run build
  args:
    chdir: "repositories/Hackaton-2021/frontend"
