# Generated by Django 3.2.6 on 2021-12-03 17:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unity_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightReport',
            fields=[
                ('guid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_report', to='unity_app.projectuser')),
            ],
            options={
                'db_table': 'flight_reports',
            },
        ),
    ]
