# Generated by Django 3.2.6 on 2021-12-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity_app', '0002_flightreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreport',
            name='danger_close',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='hits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='max_height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='max_speed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='points',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flightreport',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
